version: '3.9'

services:
  
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - feedr
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  
  feedr.gateway:
    container_name: feedr-gateway
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:80"
    networks:
      - feedr

  feedr.aggregator:
    container_name: feedr-aggregator
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5010:80"
    networks:
      - feedr
      
    
  feedr.feeds.news:
    container_name: feedr-feeds-news
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    restart: unless-stopped
    ports:
      - "5030:80"
    networks:
      - feedr

  feedr.feeds.quotes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    container_name: feedr-feeds-quotes
    restart: unless-stopped
    ports:
      - "5040:80"
    networks:
      - feedr

  feedr.feeds.weather:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    container_name: feedr-feeds-weather
    restart: unless-stopped
    ports:
      - "5050:80"
    networks:
      - feedr


  feedr.notifier:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    container_name: feedr-notifier
    restart: unless-stopped
    ports:
      - "5020:80"
    networks:
      - feedr

networks:
  feedr:
    name: feedr
    external: true

volumes:
  redis:
    driver: local   